# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
# liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    # : "gd"
liip_imagine:
    filter_sets:
        cache: ~
        squared_thumbnail_small:
            filters:
                thumbnail:
                    size:          [300, 300]
                    mode:          outbound
                    allow_upscale: true
        media_thumbnail_165:
            quality: 100
            filters:
                thumbnail:
                    size:          [165, 165]
                    mode:          outbound
                    allow_upscale: true
        media_thumbnail_small:
            quality: 100
            filters:
                thumbnail:
                    size:          [64, 64]
                    mode:          outbound
                    allow_upscale: true
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
                background: { size: [124, 94], position: center, color: '#000000' }