App\Entity\Blog\BlogImage:
  type: entity
  #repositoryClass: App\Repository\BlogImageRepository
  table: blog_image
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    image:
      type: string
      length: 255
    rank:
      type: integer
      options:
        default: 1
  manyToOne:
    post:
      targetEntity: BlogPost
      inversedBy: images
      #cascade: [ persist ]
      joinColumn:
        name: post_id
        referencedColumnName: id