App\Entity\Contact:
    type: entity
    table: contact
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        subject:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 0
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    lifecycleCallbacks:
        prePersist: [ prePersist ]