App\Entity\ResetPasswordRequest:
    type: entity
    repositoryClass: App\Repository\ResetPasswordRequestRepository
    table: reset_password_request
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        user:
            targetEntity: User